### PR TITLE
Polish translation - first step

### PR DESCRIPTION
**Pull request by JaroslawWiosna**
Hello @dabalroman and @klen 
I found issue #42 and wanted to help.

I would be glad if @dabalroman could review this pull request, but if you have already started to write your own translation, feel free to ignore me.

---

@klen, This is not full translation, since I didn't want to take this issue from @dabalroman . 
...and also I think it's better to make changes in smaller chunks instead of one monster commit, don't you think?

### CODE REVIEW

**Comment by klen** [comment]
@JaroslawWiosna Thank you for the translation. It's in the very early stage, so I won't add it to production, unfortunately.

**Comment by klen** [comment]
Not sure that @dabalroman has started yet.

**Comment by dabalroman** [comment]
I haven't started yet but I plan to in near future.

**Comment by dabalroman** [comment]
I've committed mine general translation based on @JaroslawWiosna commit in #45.

**Pull request merged**
